# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "puppetlabs/centos-6.6-64-puppet"

  config.vm.network "private_network", ip: "10.0.0.100"

  config.vm.synced_folder "../http/", "/srv/http/", type: "nfs"
  config.vm.synced_folder "../logs/nginx", "/var/log/nginx", type: "nfs"
  config.vm.synced_folder "../logs/php-fpm", "/var/log/pph-fpm", type: "nfs"

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "puppet/manifests"
  end

  config.vm.provider :virtualbox do |vb|
    vb.name = "Sandbox"
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
  end
end
